export const GET_EXERCISES = "GET_EXERCISES";
export const ADD_EXERCISE = "ADD_EXERCISE";
export const EDIT_EXERCISE = "EDIT_EXERCISE";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
export const LOADING_EXERCISES = "LOADING_EXERCISES";
